spring.application.name=prestify-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/prestify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=America/Sao_Paulo

prestify.jwt.secret=prestify-development-secret-key-change-this-before-production-2026
prestify.jwt.expiration=28800

logging.level.org.springframework.security=TRACE